/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["city.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["event.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["event.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/event-formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["eventFormat.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["industry.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metadata.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preset.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets/{preset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preset.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/priority-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["priorityEvents.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CityResource */
        CityResource: {
            id: number;
            title: string;
            events_count?: number;
        };
        /**
         * EventFormat
         * @enum {string}
         */
        EventFormat: "forum" | "conference" | "exhibition" | "seminar" | "webinar";
        /** EventFormatResource */
        EventFormatResource: {
            id: string;
            name: string;
            color: string;
        };
        /** EventResource */
        EventResource: {
            id: number;
            title: string;
            description: string | null;
            cover: {
                original: string | "";
                thumb: string | "";
                preview: string | "";
            };
            gallery: string;
            start_date: string;
            end_date: string;
            format: components["schemas"]["EventFormat"];
            website: string | null;
            city: {
                id: string;
                title: string;
            };
            industry: {
                id: string;
                title: string;
            };
            tags: string;
            sort_order: number;
            metadata: components["schemas"]["MetadataResource"];
        };
        /** IndustryResource */
        IndustryResource: {
            id: number;
            title: string;
            events_count?: number;
        };
        /** MetadataResource */
        MetadataResource: {
            title: string | null;
            h1: string | null;
            description: string | null;
            keywords: string | null;
            canonicalUrl: string;
            robots: string | null;
            openGraph?: {
                title: string | null;
                description: string | null;
                type: string | null;
                image: string | null;
                url: string | null;
                siteName: string | null;
                locale: string | null;
            };
            twitter?: {
                card: string | null;
                title: string | null;
                description: string | null;
                image: string | null;
                site: string | null;
                creator: string | null;
            };
        };
        /** PresetDetailResource */
        PresetDetailResource: {
            id: string;
            title: string;
            slug: string;
            filters: string;
            events: components["schemas"]["SearchEventsResource"];
        };
        /** PresetResource */
        PresetResource: {
            id: number;
            title: string;
            slug: string;
            filters: unknown[];
        };
        /** SearchEventsResource */
        SearchEventsResource: {
            data: components["schemas"]["EventResource"][];
            facets: {
                formats: string;
                cities: string;
                industries: string;
            };
            meta: {
                total: string;
                per_page: string;
                current_page: string;
                last_page: string;
            };
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        NotFoundHttpException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "city.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `CityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CityResource"][];
                    };
                };
            };
        };
    };
    "event.index": {
        parameters: {
            query?: {
                query?: string | null;
                format?: components["schemas"]["EventFormat"];
                city_id?: number | null;
                industry_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                per_page?: number | null;
                page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SearchEventsResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchEventsResource"];
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "event.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "eventFormat.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `EventFormatResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventFormatResource"][];
                    };
                };
            };
        };
    };
    "industry.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `IndustryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["IndustryResource"][];
                    };
                };
            };
        };
    };
    "metadata.show": {
        parameters: {
            query: {
                type: "event" | "metadata";
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `MetadataResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MetadataResource"];
                    };
                };
            };
            404: components["responses"]["NotFoundHttpException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "preset.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `PresetResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PresetResource"][];
                    };
                };
            };
        };
    };
    "preset.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The preset ID */
                preset: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PresetDetailResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PresetDetailResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "priorityEvents.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `EventResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventResource"][];
                    };
                };
            };
        };
    };
}
